# Label to use when marking as stale
staleLabel: inactive

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

closeComment: Stale-bot has closed this stale item. Please reopen it if this is in error.

pulls:
  daysUntilStale: 14
  daysUntilClose: 3
  exemptLabels:
    - bug
    - hotfix
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed within a week if no further activity occurs, but it
    only takes a comment to keep a contribution alive :) Also, even if it is closed,
    you can always reopen the PR when you're ready. Thank you for contributing.


issues:
  daysUntilStale: 30
  daysUntilClose: 3
  exemptLabels:
    - validated
  markComment: >
    This issue is being marked `inactive` because there hasn't been any activity in 30 days.
    Please leave a comment if you think this issue is still relevant and should be prioritized,
    otherwise it will be automatically closed in 3 days (you can always reopen it later).
